CREATE TABLE Team(
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(100) NOT NULL,
foundation_year INTEGER NOT NULL,
world_cups_won INTEGER NOT NULL,
entry_fee_paid BOOLEAN NOT NULL,
valid BOOLEAN NOT NULL DEFAULT true
);